### ISSUE TITLE
I cant render more than one of the same polygon using my algorithm

### ISSUE THREAD

**Issue by RinzuTheCoder** [giawa/opengl4csharp#34] opened 2020-03-28 19:40 UTC
![Shape2d image](https://user-images.githubusercontent.com/20666756/77832147-1893f380-70f1-11ea-94a0-5de5121bcf43.PNG)
![draw shape image](https://user-images.githubusercontent.com/20666756/77832161-2d708700-70f1-11ea-983e-4490667ebb49.PNG)
![draw shapes image](https://user-images.githubusercontent.com/20666756/77832162-2e091d80-70f1-11ea-9967-337f93c01bd5.PNG)
![More than one shape](https://user-images.githubusercontent.com/20666756/77832172-3eb99380-70f1-11ea-9a06-97bdefdace15.PNG)

![Shapefactory image](https://user-images.githubusercontent.com/20666756/77832151-2184c500-70f1-11ea-90cb-76046bbd75e0.PNG)
![createDisplay](https://user-images.githubusercontent.com/20666756/77832267-02d2fe00-70f2-11ea-8d5a-aece46e161b4.PNG)

**Comment by giawa** [comment] 2020-03-28 20:13
Do you mind providing a minimum reproduction case along with expected and actual results via gist or a github repo?

**Comment by giawa** [comment] 2020-04-16 20:51
Do you have any update on this?  I'll mark as closed in the coming days if it cannot be reproduced.  Thanks!

**Comment by giawa** [comment] 2020-04-17 01:50
Let me know if you track down a minimum reproduction case (or if this is still even an issue).  I'll close this issue for now, since it is an older issue.

**Closed as completed by giawa** 2020-04-17 01:50 UTC

**Comment by RinzuTheCoder** [comment] 2020-04-17 01:51
Got it

**Comment by RinzuTheCoder** [comment] 2020-04-17 01:53
Please reopen lost the link and ny comments

**Comment by giawa** [comment] 2020-04-17 01:54
The whole history should be here:  https://github.com/giawa/opengl4csharp/issues/34
